### ISSUE TITLE
No Bluetooth Device Found

### ISSUE THREAD

**Issue by ibnuzaini** [lucianopereira86/Quasar-PWA-Bluetooth-Printer#2]
Hi.. I run the demo but no device found. Whenever I use another demo from https://github.com/WebBluetoothCG/demos/tree/gh-pages/bluetooth-printer, my bluetooth printer detected. Any suggestion?

Solved. Tks.

**Comment by lucianopereira86** [comment]
Probably your thermal printer is paired with another device. 
Try to restart it.

**Comment by ibnuzaini** [comment]
You are right, the device found after restart.
