### ISSUE TITLE
Do print function will be fine when I build to cordova android?

### ISSUE THREAD

**Issue by ibnuzaini** [lucianopereira86/Quasar-PWA-Bluetooth-Printer#3]
Hi.. thanks for the great example. i succeed deploy pwa to firebase and the print function still work fine. But when i build on android version using your guide (https://github.com/lucianopereira86/Quasar-Cordova-Apk) the search device window not appear. what should I do? please guide.

**Comment by lucianopereira86** [comment]
It's because the "navigator.bluetooth" works only in a browser.
Android needs a cordova plugin to connect with Bluetooth.
